#!/usr/bin/env bash
# Setup script for Zaxy.
# Generates .env file, creates directories, and validates Docker services.
# Usage: ./scripts/setup.sh [--production]

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
ENV_FILE="${PROJECT_ROOT}/.env"
MODE="${1:-dev}"

echo "🚀 Zaxy Setup (${MODE})"
echo "   Project root: ${PROJECT_ROOT}"

# ------------------------------------------------------------------
# Generate .env if missing
# ------------------------------------------------------------------
if [[ ! -f "${ENV_FILE}" ]]; then
    echo "📝 Generating ${ENV_FILE}..."

    if [[ "${MODE}" == "--production" ]]; then
        # Strong random password for production
        NEO4J_PASSWORD="$(openssl rand -hex 32)"
        LOG_FORMAT="json"
    else
        # Dev defaults
        NEO4J_PASSWORD="testpassword"
        LOG_FORMAT="console"
    fi

    cat > "${ENV_FILE}" <<EOF
# Auto-generated by scripts/setup.sh on $(date -Iseconds)
# Mode: ${MODE}

NEO4J_URI=bolt://neo4j:7687
NEO4J_USER=neo4j
NEO4J_PASSWORD=${NEO4J_PASSWORD}
NEO4J_DATABASE=neo4j

EVENTLOOM_PATH=.eventloom
EVENTLOOM_THREAD=default

PATHLIGHT_URL=http://pathlight-collector:4100

SERVER_NAME=zaxy-memory

LOG_LEVEL=INFO
LOG_FORMAT=${LOG_FORMAT}

QUERY_DEFAULT_LIMIT=10
EOF

    echo "   ✅ Created ${ENV_FILE}"
    if [[ "${MODE}" == "--production" ]]; then
        echo "   🔒 Neo4j password: ${NEO4J_PASSWORD:0:8}... (saved in .env)"
    fi
else
    echo "   ℹ️  ${ENV_FILE} already exists, skipping generation"
fi

# ------------------------------------------------------------------
# Create directories
# ------------------------------------------------------------------
mkdir -p "${PROJECT_ROOT}/.eventloom"
mkdir -p "${PROJECT_ROOT}/.volumes/neo4j_data"
mkdir -p "${PROJECT_ROOT}/.volumes/neo4j_logs"

echo "   ✅ Created directories"

# ------------------------------------------------------------------
# Validate Docker
# ------------------------------------------------------------------
if ! command -v docker &> /dev/null; then
    echo "   ❌ Docker is not installed"
    exit 1
fi

if ! docker compose version &> /dev/null && ! docker-compose version &> /dev/null; then
    echo "   ❌ Docker Compose is not installed"
    exit 1
fi

echo "   ✅ Docker available"

# ------------------------------------------------------------------
# Summary
# ------------------------------------------------------------------
echo ""
echo "📋 Setup complete. Next steps:"
echo ""
if [[ "${MODE}" == "--production" ]]; then
    echo "   docker compose -f docker-compose.prod.yml up -d"
else
    echo "   docker compose up -d"
    echo "   pytest -m integration"
fi
echo ""
